os: linux
dist: xenial
language: node_js
node_js:
  - 10
cache: yarn
env:
  - PORT=3000
script:
  - yarn test:coverage
after_success:
  - codecov -f coverage/*.json
notifications:	
  email:	
    on_success: never	
    on_failure: never